### PR TITLE
81 addon review save bug

### LINKED ISSUE #81: Addon Review not loading correctly from the foodDiary.json file

### PR DESCRIPTION
**Pull request by Prabhakaran-Gokul**
Changed the implementation of addon review, similar to Tags but using ArrayList instead.

### CODE REVIEW

File: src/main/java/fooddiary/logic/commands/AddOnCommand.java [hunk 1]
```diff
@@ -91,17 +93,16 @@ private static Entry createUpdatedEntry(Entry entryToAddOn, AddOnToEntryDescript
         Name updatedName = entryToAddOn.getName(); //cannot add on name
         Rating updatedRating = entryToAddOn.getRating();
         Price updatedPrice = entryToAddOn.getPrice();
-        Review updatedReview = entryToAddOn.getReview(); //TODO try not to violate Demeter's Law
-        addOnToEntryDescriptor.getReview().ifPresent(review -> {
-            updatedReview.addReview(review.value);
-        });
+        List<Review> updatedReviews = new ArrayList<>();
+        updatedReviews.addAll(entryToAddOn.getReviews());
+        addOnToEntryDescriptor.getReviews().ifPresent(r -> updatedReviews.addAll(r));
```
Comment (marcusleeeugene) [inline src/main/java/fooddiary/logic/commands/AddOnCommand.java:98]: Good use of ifPresent!

**Review by marcusleeeugene — APPROVED** [review]
